# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_dockwidget_example.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.dockWidget = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget.setObjectName("dockWidget")

        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.graphicsView_cb = PlotWidget(self.dockWidgetContents)
        self.graphicsView_cb.setObjectName("graphicsView_cb")
        self.gridLayout_2.addWidget(self.graphicsView_cb, 2, 1, 1, 1)

        self.doubleSpinBox_per_min = ScienDSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_per_min.setObjectName("doubleSpinBox_per_min")
        self.gridLayout_2.addWidget(self.doubleSpinBox_per_min, 3, 1, 1, 1)

        self.doubleSpinBox_val_max = ScienDSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_val_max.setObjectName("doubleSpinBox_val_max")
        self.gridLayout_2.addWidget(self.doubleSpinBox_val_max, 0, 1, 1, 1)

        self.radioButton_man = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButton_man.setChecked(True)
        self.radioButton_man.setObjectName("radioButton_man")
        self.gridLayout_2.addWidget(self.radioButton_man, 5, 1, 1, 1)

        self.radioButton_per = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButton_per.setObjectName("radioButton_per")
        self.gridLayout_2.addWidget(self.radioButton_per, 6, 1, 1, 1)

        self.doubleSpinBox_val_min = ScienDSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_val_min.setObjectName("doubleSpinBox_val_min")
        self.gridLayout_2.addWidget(self.doubleSpinBox_val_min, 4, 1, 1, 1)

        self.graphicsView_data = QtWidgets.QGraphicsView(self.dockWidgetContents)
        self.graphicsView_data.setObjectName("graphicsView_data")
        self.gridLayout_2.addWidget(self.graphicsView_data, 0, 0, 7, 1)

        self.doubleSpinBox_per_max = ScienDSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_per_max.setObjectName("doubleSpinBox_per_max")
        self.gridLayout_2.addWidget(self.doubleSpinBox_per_max, 1, 1, 1, 1)

        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_man.setText(_translate("MainWindow", "Manual"))
        self.radioButton_per.setText(_translate("MainWindow", "Percentile"))
from pyqtgraph import PlotWidget
from qtwidgets.scientific_spinbox import ScienDSpinBox
